save point

diff --git a/.github/workflows/blueGreen.yml b/.github/workflows/blueGreen.yml
--- a/.github/workflows/blueGreen.yml
+++ b/.github/workflows/blueGreen.yml
@@ -1,107 +1,107 @@
-# name: DevSecOps Pipeline
+name: DevSecOps Pipeline
 
-# on:
-#   push:
-#     branches:
-#       - main
-#       - dev
-#   pull_request:
-#     branches:
-#       - main
+on:
+  push:
+    branches:
+      - main
+      - dev
+  pull_request:
+    branches:
+      - main
 
-# jobs:
-#   build:
-#     runs-on: ubuntu-latest
-#     steps:
-#       - name: Checkout code
-#         uses: actions/checkout@v2
+jobs:
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-#       - name: Install dependencies
-#         run: |
-#           # sudo apt-get update -y
-#           # sudo apt-get install -y awscli
-#           echo "Update complete"
+      - name: Install dependencies
+        run: |
+          # sudo apt-get update -y
+          # sudo apt-get install -y awscli
+          echo "Update complete"
 
-#       - name: Configure AWS credentials
-#         run: |
-#           export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
-#           export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
-#           echo "Build complete"
+      - name: Configure AWS credentials
+        run: |
+          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
+          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
+          echo "Build complete"
 
-#   test:
-#     runs-on: ubuntu-latest
-#     needs: build
-#     steps:
-#       - name: Checkout code
-#         uses: actions/checkout@v2
+  test:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-#       - name: Install dependencies
-#         run: |
-#           # sudo apt-get update
-#           # sudo apt-get install -y awscli
-#           echo "Test complete"
+      - name: Install dependencies
+        run: |
+          # sudo apt-get update
+          # sudo apt-get install -y awscli
+          echo "Test complete"
 
-#       - name: Test CloudFormation template
-#         run: |
-#           if grep -q "turnthepage" template.yml; then
-#             echo "Template contains the string 'turnthepage'"
-#           else
-#             echo "Template does not contain the string 'turnthepage'"
-#           fi
+      - name: Test CloudFormation template
+        run: |
+          if grep -q "turnthepage" template.yml; then
+            echo "Template contains the string 'turnthepage'"
+          else
+            echo "Template does not contain the string 'turnthepage'"
+          fi
 
-#   security-scan:
-#     runs-on: ubuntu-latest
-#     needs: ["test","build"]
-#     steps:
-#       - name: Checkout code
-#         uses: actions/checkout@v2
+  security-scan:
+    runs-on: ubuntu-latest
+    needs: ["test","build"]
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
 
-#       - name: Install dependencies
-#         run: |
-#           sudo apt-get update -y
-#           sudo apt-get install -y awscli
-#           # echo "Test complete"
+      - name: Install dependencies
+        run: |
+          sudo apt-get update -y
+          sudo apt-get install -y awscli
+          # echo "Test complete"
 
-#       - name: Run security scan
-#         run: |
-#           if grep -q "your_regex_pattern"  2_EC2_ELK_STACK.yml; then
-#             echo "Regex pattern found in template_grafana.yml. Proceeding with deployment."
-#             exit 1
-#           else
-#             echo "Regex pattern not found in template_grafana.yml. Stopping deployment."
-#           fi
+      - name: Run security scan
+        run: |
+          if grep -q "your_regex_pattern"  2_EC2_ELK_STACK.yml; then
+            echo "Regex pattern found in template_grafana.yml. Proceeding with deployment."
+            exit 1
+          else
+            echo "Regex pattern not found in template_grafana.yml. Stopping deployment."
+          fi
 
-#   deploy:
-#     runs-on: ubuntu-latest
-#     needs: ["security-scan","test","build"]
-#     steps:
-#       - uses: actions/checkout@v2
+  deploy:
+    runs-on: ubuntu-latest
+    needs: ["security-scan","test","build"]
+    steps:
+      - uses: actions/checkout@v2
 
-#       - name: Install AWS CLI
-#         run: |
-#           sudo apt-get update -y
-#           sudo apt-get install -y awscli
-#           # echo "Update complete"
+      - name: Install AWS CLI
+        run: |
+          sudo apt-get update -y
+          sudo apt-get install -y awscli
+          # echo "Update complete"
 
-#       - name: Set AWS Credentials and Deploy CloudFormation stack
-#         run: |
-#           # if [ ${{ github.ref == 'refs/heads/dev' }} ]; then
-#           #   export AWS_ACCESS_KEY_ID="${{ secrets.ACCOUNT_B_AWS_ACCESS_KEY_ID }}"
-#           #   export AWS_SECRET_ACCESS_KEY="${{ secrets.ACCOUNT_B_AWS_SECRET_ACCESS_KEY }}"
-#           #   export AWS_DEFAULT_REGION=us-east-1
-#           #   aws cloudformation deploy \
-#           #     --template-file template_stable_diff.yml \
-#           #     --stack-name sreuniversitydev \
-#           #     --parameter-overrides Environment=prod StackName=sreuniversityelk
-#           # else
-#             export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
-#             export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
-#             export AWS_DEFAULT_REGION=us-east-1
-#             aws cloudformation deploy \
-#               --template-file 2_EC2_ELK_STACK.yml \
-#               --stack-name sreuniversityelk \
-#               --parameter-overrides Environment=prod StackName=sreuniversityelk
-#           # fi
+      - name: Set AWS Credentials and Deploy CloudFormation stack
+        run: |
+          # if [ ${{ github.ref == 'refs/heads/dev' }} ]; then
+          #   export AWS_ACCESS_KEY_ID="${{ secrets.ACCOUNT_B_AWS_ACCESS_KEY_ID }}"
+          #   export AWS_SECRET_ACCESS_KEY="${{ secrets.ACCOUNT_B_AWS_SECRET_ACCESS_KEY }}"
+          #   export AWS_DEFAULT_REGION=us-east-1
+          #   aws cloudformation deploy \
+          #     --template-file template_stable_diff.yml \
+          #     --stack-name sreuniversitydev \
+          #     --parameter-overrides Environment=prod StackName=sreuniversityelk
+          # else
+          #   export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
+          #   export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
+          #   export AWS_DEFAULT_REGION=us-east-1
+          #   aws cloudformation deploy \
+          #     --template-file 2_EC2_ELK_STACK.yml \
+          #     --stack-name sreuniversityelk \
+          #     --parameter-overrides Environment=prod StackName=sreuniversityelk
+          # # fi
 
 
 
