save point

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -9,60 +9,61 @@ on:
       - main
 
 jobs:
-  # build:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v2
-  #     - name: Install dependencies
-  #       run: |
-  #         sudo apt-get update
-  #         sudo apt-get install -y awscli
-  #     - name: Configure AWS credentials
-  #       run: |
-  #         export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
-  #         export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
-  #         echo "Build complete"
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Install dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y awscli
+      - name: Configure AWS credentials
+        run: |
+          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
+          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
+          echo "Build complete"
 
-  # test:
-  #   runs-on: ubuntu-latest
-  #   needs: build
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v2
-  #     - name: Install dependencies
-  #       run: |
-  #         sudo apt-get update
-  #         sudo apt-get install -y awscli
-  #     - name: Test CloudFormation template
-  #       run: |
-  #         if grep -q "turnthepage" template.yml; then
-  #           echo "Template contains the string 'turnthepage'"
-  #         else
-  #           echo "Template does not contain the string 'turnthepage'"
-  #         fi
+  test:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Install dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y awscli
+      - name: Test CloudFormation template
+        run: |
+          if grep -q "turnthepage" template.yml; then
+            echo "Template contains the string 'turnthepage'"
+          else
+            echo "Template does not contain the string 'turnthepage'"
+          fi
 
-  # security-scan:
-  #   runs-on: ubuntu-latest
-  #   needs: build
-  #   steps:
-  #     - name: Checkout code
-  #       uses: actions/checkout@v2
-  #     - name: Install dependencies
-  #       run: |
-  #         sudo apt-get update
-  #         sudo apt-get install -y awscli
-  #     - name: Run security scan
-  #       run: |
-  #         if grep -q "your_regex_pattern" template.yml; then
-  #           echo "Regex pattern found in template.yml. Proceeding with deployment."
-  #           exit 1
-  #         else
-  #           echo "Regex pattern not found in template.yml. Stopping deployment."
-  #         fi
+  security-scan:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Install dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y awscli
+      - name: Run security scan
+        run: |
+          if grep -q "your_regex_pattern" template.yml; then
+            echo "Regex pattern found in template.yml. Proceeding with deployment."
+            exit 1
+          else
+            echo "Regex pattern not found in template.yml. Stopping deployment."
+          fi
 
   deploy:
     runs-on: ubuntu-latest
+    needs: ["security-scan","test","build"]
     steps:
       - uses: actions/checkout@v2
       - name: Install AWS CLI
